In [267]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mp
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from joblib import dump

In [268]:
df = pd.read_csv(r"C:\Users\Pavilion\Documents\Coding Languages\Artificial Intelligence\Excel and Csv\hotel bookings.csv")

In [269]:
pd.set_option('display.max_columns',None)

In [270]:
HotelLE = LabelEncoder()
Arrival_Date_MonthLE = LabelEncoder()
MealLE = LabelEncoder()
CountryLE = LabelEncoder()
Distribution_ChannelLE = LabelEncoder()
Deposit_Type = LabelEncoder()
Customer_Type = LabelEncoder()
Is_Cancelled = LabelEncoder()
Reserved_Room_Type = LabelEncoder()
scaler = StandardScaler()
model = RandomForestClassifier(n_estimators = 150)
dtc = DecisionTreeClassifier(criterion = 'entropy')
knn = KNeighborsClassifier(n_neighbors = 150)
logic = LogisticRegression()
SVCLinear = SVC(kernel = 'linear')
SVCRBF = SVC(kernel = 'rbf')
SVCPoly = SVC(kernel = 'poly')

In [271]:
df2

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,1,0,342,2015.0,5,27,1.0,0,0,2,0.0,0,0,135,1,0,0,0,2,0,0,2,0.000,0,0.0
1,1,0,373,2015.0,5,27,1.0,0,0,2,0.0,0,0,135,1,0,0,0,2,0,0,2,0.000,0,0.0
2,1,0,7,2015.0,5,27,1.0,0,1,2,0.0,0,0,59,1,0,0,0,0,0,0,2,75.000,0,0.0
3,1,0,13,2015.0,5,27,1.0,0,1,2,0.0,0,0,59,0,0,0,0,0,0,0,2,75.000,0,0.0
4,1,0,14,2015.0,5,27,1.0,0,2,2,0.0,0,0,59,3,0,0,0,0,0,0,2,98.000,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,0,23,2017.0,1,35,30.0,2,5,2,0.0,0,0,15,3,0,0,0,0,0,0,2,96.140,0,0.0
119386,0,0,102,2017.0,1,35,31.0,2,5,2,0.0,0,0,56,3,0,0,0,4,0,0,2,211.065,0,2.0
119387,0,0,34,2017.0,1,35,31.0,2,5,2,0.0,0,0,43,3,0,0,0,3,0,0,2,157.710,0,2.5
119388,0,0,109,2017.0,1,35,31.0,2,5,2,0.0,0,0,59,3,0,0,0,0,0,0,2,104.400,0,0.0
119389,0,0,205,2017.0,1,35,29.0,2,6,2,0.0,0,2,43,3,0,0,0,0,0,0,2,151.200,0,2.0

In [272]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [273]:
df2 = df.copy()

In [274]:
df2 = df2.drop(columns = ['company','agent','assigned_room_type','market_segment','reservation_status','reservation_status_date','booking_changes'])

In [275]:
df2['meal'].value_counts()

meal
BB           92310
HB           14463
SC           10650
Undefined     1169
FB             798
Name: count, dtype: int64

In [276]:
df2

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,0,0,0,C,No Deposit,0,Transient,0.00,0,0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,0,0,0,C,No Deposit,0,Transient,0.00,0,0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,0,0,0,A,No Deposit,0,Transient,75.00,0,0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,0,0,0,A,No Deposit,0,Transient,75.00,0,0
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,TA/TO,0,0,0,A,No Deposit,0,Transient,98.00,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,TA/TO,0,0,0,A,No Deposit,0,Transient,96.14,0,0
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,TA/TO,0,0,0,E,No Deposit,0,Transient,225.43,0,2
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,TA/TO,0,0,0,D,No Deposit,0,Transient,157.71,0,4
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,TA/TO,0,0,0,A,No Deposit,0,Transient,104.40,0,0
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,TA/TO,0,0,0,A,No Deposit,0,Transient,151.20,0,2

In [277]:
df2.isnull().sum()

hotel                               0
is_canceled                         0
lead_time                           0
arrival_date_year                   0
arrival_date_month                  0
arrival_date_week_number            0
arrival_date_day_of_month           0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            4
babies                              0
meal                                0
country                           488
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
reserved_room_type                  0
deposit_type                        0
days_in_waiting_list                0
customer_type                       0
adr                                 0
required_car_parking_spaces         0
total_of_special_requests           0
dtype: int64

In [278]:
df2 = df2.fillna(df2['country'].mode()[0])

In [279]:
df2.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
dtype: int64

In [280]:
intvar = df2.select_dtypes(include = ['int','float'])
obvar = df2.select_dtypes(include = 'object')

In [281]:
obvar.columns

Index(['hotel', 'arrival_date_month', 'children', 'meal', 'country',
       'distribution_channel', 'reserved_room_type', 'deposit_type',
       'customer_type'],
      dtype='object')

In [282]:
intvar = intvar.drop(columns = 'is_canceled')

In [283]:
intvar.columns

Index(['lead_time', 'arrival_date_year', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'babies', 'is_repeated_guest',
       'previous_cancellations', 'previous_bookings_not_canceled',
       'days_in_waiting_list', 'adr', 'required_car_parking_spaces',
       'total_of_special_requests'],
      dtype='object')

In [284]:
def Outliers(df,columns):
    for i in columns:
        q1 = df[i].quantile(0.25)
        q3 = df[i].quantile(0.75)
        iqr = q3 - q1
        upperlimit = q3 + (1.5 * iqr)
        lowerlimit = q1 - (1.5 * iqr)
        df.loc[(df[i] > upperlimit),i] = upperlimit
        df.loc[(df[i] < lowerlimit), i] = lowerlimit
    return df
df2 = Outliers(df2,intvar.columns)

C:\Users\Pavilion\AppData\Local\Temp\ipykernel_9800\403251963.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2018.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[i] > upperlimit),i] = upperlimit
C:\Users\Pavilion\AppData\Local\Temp\ipykernel_9800\403251963.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '45.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[i] > upperlimit),i] = upperlimit
C:\Users\Pavilion\AppData\Local\Temp\ipykernel_9800\403251963.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df[i] > upperlimit),i] = upperlimit

In [293]:
df2['is_canceled'] = df2['is_canceled'].replace(1,'Yes')
df2['is_canceled'] = df2['is_canceled'].replace(0,'No')
df2['hotel'] = HotelLE.fit_transform(df2['hotel'])
df2['arrival_date_month'] = Arrival_Date_MonthLE.fit_transform(df2['arrival_date_month'])
df2['meal'] = MealLE.fit_transform(df2['meal'])
df2['country'] = CountryLE.fit_transform(df2['country'])
df2['distribution_channel'] = Distribution_ChannelLE.fit_transform(df2['distribution_channel'])
df2['deposit_type'] = Deposit_Type.fit_transform(df2['deposit_type'])
df2['customer_type'] = Customer_Type.fit_transform(df2['customer_type'])
df2['is_canceled'] = Is_Cancelled.fit_transform(df2['is_canceled'])
df2['reserved_room_type'] = Reserved_Room_Type.fit_transform(df2['reserved_room_type'])

In [292]:
df2['children'] = pd.to_numeric(df2['children'],errors = 'coerce')

In [291]:
x = df2.drop(columns = 'is_canceled')
y = df2['is_canceled']

In [290]:
df2['children'] = df2['children'].fillna(df2['children'].median())

In [289]:
df2.isnull().sum().sum()

np.int64(0)

In [294]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,random_state = 70, test_size = 0.3)

In [295]:
scaler.fit(xtrain)
xtrainscaled = scaler.transform(xtrain)
xtestscaled = scaler.transform(xtest)

In [296]:
logic.fit(xtrainscaled,ytrain)
logic.score(xtestscaled,ytest)

0.7700254069296703

In [297]:
dtc.fit(xtrainscaled,ytrain)
dtc.score(xtestscaled,ytest)

0.8299131697238742

In [298]:
model.fit(xtrainscaled,ytrain)
model.score(xtestscaled,ytest)

0.8732724683809364

In [299]:
knn.fit(xtrainscaled,ytrain)
knn.score(xtestscaled,ytest)

0.7958790518468883

In [ ]:
SVCLinear.fit(xtrainscaled,ytrain)
SVCLinear.score(xtestscaled,ytrain)

In [ ]:
SVCPoly.fit(xtrainscaled,ytrain)
SVCPoly.score(xtestscaled,ytest)

In [ ]:
SVCRBF.fit(xtrainscaled,ytrain)
SVCRBF.score(xtestscaled,ytest)