In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mp
import sklearn as slice
import seaborn as sns

In [22]:
df = pd.read_csv('Bengaluru_House_Data.csv')

In [13]:
df.shape

(13320, 9)

In [14]:
null_var = df.isnull().sum()/df.shape[0]*100

In [15]:
dc = null_var[null_var>20].keys()

In [16]:
df2 = df.drop(columns=dc)

In [17]:
fill = df2.select_dtypes(include=(int,float))

In [18]:
df = df2.fillna(fill.mean())

In [30]:
dummy = pd.get_dummies(df)
dummy

,bath,balcony,price,area_type_Built-up Area,area_type_Carpet Area,area_type_Plot Area,area_type_Super built-up Area,availability_14-Jul,availability_14-Nov,availability_15-Aug,...,total_sqft_990,total_sqft_991,total_sqft_992,total_sqft_993,total_sqft_994,total_sqft_995,total_sqft_996,total_sqft_997,total_sqft_998,total_sqft_999
0,2.0,1.0,39.07,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,5.0,3.0,120.00,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2.0,3.0,62.00,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,3.0,1.0,95.00,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,2.0,1.0,51.00,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,4.0,0.0,231.00,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13316,5.0,NaN,400.00,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13317,2.0,1.0,60.00,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13318,4.0,1.0,488.00,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13319,1.0,1.0,17.00,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [34]:
boolval = dummy.select_dtypes('bool')
boolval

,area_type_Built-up Area,area_type_Carpet Area,area_type_Plot Area,area_type_Super built-up Area,availability_14-Jul,availability_14-Nov,availability_15-Aug,availability_15-Dec,availability_15-Jun,availability_15-Nov,...,total_sqft_990,total_sqft_991,total_sqft_992,total_sqft_993,total_sqft_994,total_sqft_995,total_sqft_996,total_sqft_997,total_sqft_998,total_sqft_999
0,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13315,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13316,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13317,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13318,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13319,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [46]:
int_val = boolval.astype(int)

In [47]:
df[dummy].replace(int_val)

ValueError: Boolean array expected for the condition, not object